{{- if and .Values.ingress.enabled .Values.ingress.letsEncrypt.enabled (.Values.ingress.letsEncrypt.email) }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "spacebar.fullname" . }}-tls
  labels:
    {{- include "spacebar.labels" . | nindent 4 }}
spec:
  secretName: {{ include "spacebar.fullname" . }}-tls
  issuerRef:
    name: {{ .Values.ingress.letsEncrypt.clusterIssuer | default (printf "%s-letsencrypt" (include "spacebar.fullname" .)) }}
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.ingress.host | quote }}
{{- end }}
